create branch 5.8

diff --git a/src/etc/rc b/src/etc/rc
--- a/src/etc/rc
+++ b/src/etc/rc
@@ -1,14 +1,17 @@
-#	$OpenBSD: rc,v 1.447 2015/01/22 19:00:24 krw Exp $
+#	$OpenBSD: rc,v 1.455 2015/08/03 04:19:25 yasuoka Exp $
 
-# System startup script run by init on autoboot
-# or after single-user.
-# Output and error are redirected to console by init,
-# and the console is the controlling terminal.
+# System startup script run by init on autoboot or after single-user.
+# Output and error are redirected to console by init, and the console is the
+# controlling terminal.
+
+# Turn off Strict Bourne shell.
+set +o sh
 
 # Subroutines (have to come first).
 
-# Strip comments (and leading/trailing whitespace if IFS is set)
-# from a file and spew to stdout
+
+# Strip comments (and leading/trailing whitespace if IFS is set) from a file
+# and spew to stdout.
 stripcom() {
 	local _file="$1"
 	local _line
@@ -16,13 +19,13 @@ stripcom() {
 	{
 		while read _line ; do
 			_line=${_line%%#*}		# strip comments
-			test -z "$_line" && continue
+			[ -z "$_line" ] && continue
 			echo $_line
 		done
-	} < $_file
+	} <$_file
 }
 
-# Update resource limits when sysctl changes
+# Update resource limits when sysctl changes.
 # Usage: update_limit -X loginconf_name
 update_limit() {
 	local _fl="$1"	# ulimit flag
@@ -51,8 +54,9 @@ update_limit() {
 	done
 }
 
+# Apply sysctl(8) settings.
 sysctl_conf() {
-	test -s /etc/sysctl.conf || return
+	[ -s /etc/sysctl.conf ] || return
 
 	# delete comments and blank lines
 	set -- `stripcom /etc/sysctl.conf`
@@ -71,23 +75,23 @@ sysctl_conf() {
 	done
 }
 
-mixerctl_conf()
-{
-	test -s /etc/mixerctl.conf || return
+# Apply mixerctl(1) settings.
+mixerctl_conf() {
+	[ -s /etc/mixerctl.conf ] || return
 
 	# delete comments and blank lines
 	set -- `stripcom /etc/mixerctl.conf`
 	while [ $# -ge 1 ] ; do
-		mixerctl -q $1 > /dev/null 2>&1
+		mixerctl -q $1 >/dev/null 2>&1
 		shift
 	done
 }
 
-wsconsctl_conf()
-{
+# Apply wscons system driver settings using wsconsctl(8).
+wsconsctl_conf() {
 	local save_IFS="$IFS"
 
-	test -x /sbin/wsconsctl -a -s /etc/wsconsctl.conf || return
+	[ -x /sbin/wsconsctl -a -s /etc/wsconsctl.conf ] || return
 	# delete comments and blank lines
 	IFS="
 "
@@ -99,8 +103,7 @@ wsconsctl_conf()
 	done
 }
 
-random_seed()
-{
+random_seed() {
 	# push the old seed into the kernel
 	dd if=/var/db/host.random of=/dev/random bs=65536 count=1 status=none
 	chmod 600 /var/db/host.random
@@ -111,8 +114,10 @@ random_seed()
 	chmod 600 /etc/random.seed
 }
 
-fill_baddynamic()
-{
+# Populate net.inet.(tcp|udp).baddynamic with the contents of /etc/services so
+# as to avoid randomly allocating source ports that correspond to well-known
+# services.
+fill_baddynamic() {
 	local _service=$1
 	local _sysctl="net.inet.${_service}.baddynamic"
 	stripcom /etc/services |
@@ -131,8 +136,9 @@ fill_baddynamic()
 	}
 }
 
-start_daemon()
-{
+# Start daemon using the rc.d daemon control scripts.
+# Usage: start_daemon daemon1 daemon2 daemon3
+start_daemon() {
 	local _n
 	for _n; do
 		eval _do=\${${_n}_flags}
@@ -142,8 +148,8 @@ start_daemon()
 	done
 }
 
-make_keys()
-{
+# Generate keys for isakmpd, iked and sshd if the don't exist yet.
+make_keys() {
 	if [ ! -f /etc/isakmpd/private/local.key ]; then
 		echo -n "openssl: generating isakmpd/iked RSA key... "
 		if openssl genrsa -out /etc/isakmpd/private/local.key 2048 \
@@ -168,10 +174,9 @@ make_keys()
 	ssh-keygen -A
 }
 
-# create Unix sockets directories for X if needed and make sure they have
-# correct permissions
-setup_X_sockets()
-{
+# Create Unix sockets directories for X if needed and make sure they have
+# correct permissions.
+setup_X_sockets() {
 	if [ -d /usr/X11R6/lib ]; then
 		for d in /tmp/.X11-unix /tmp/.ICE-unix ; do
 			if [ -d $d ]; then
@@ -192,8 +197,8 @@ setup_X_sockets()
 	fi
 }
 
-do_fsck()
-{
+# Check filesystems, optionally by using a flag for fsck(8) passed as $1.
+do_fsck() {
 	local _flags=$1
 
 	fsck -p $_flags
@@ -218,7 +223,7 @@ do_fsck()
 		exit 1
 		;;
 	130)
-		# interrupt before catcher installed
+		# Interrupt before catcher installed.
 		exit 1
 		;;
 	*)
@@ -228,29 +233,29 @@ do_fsck()
 	esac
 }
 
-# End subroutines
+# End subroutines.
 
 stty status '^T'
 
-# Set shell to ignore SIGINT (2), but not children;
-# shell catches SIGQUIT (3) and returns to single user after fsck.
+# Set shell to ignore SIGINT (2), but not children; shell catches SIGQUIT (3)
+# and returns to single user after fsck.
 trap : 2
-trap : 3	# shouldn't be needed
+trap : 3	# Shouldn't be needed.
 
 HOME=/; export HOME
 INRC=1; export INRC
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 export PATH
 
-# must set the domainname before rc.conf, so YP startup choices can be made
+# Must set the domainname before rc.conf, so YP startup choices can be made.
 if [ -f /etc/defaultdomain ]; then
 	domainname `stripcom /etc/defaultdomain`
 fi
 
-# need to get local functions from rc.subr
+# Need to get local functions from rc.subr.
 FUNCS_ONLY=1 . /etc/rc.d/rc.subr
 
-# load rc.conf into scope
+# Load rc.conf into scope.
 _rc_parse_conf
 
 if [ X"$1" = X"shutdown" ]; then
@@ -279,7 +284,7 @@ if [ X"$1" = X"shutdown" ]; then
 		echo single user: not running shutdown scripts
 	fi
 
-	# bring carp interfaces down gracefully
+	# Bring carp interfaces down gracefully.
 	ifconfig | while read a b; do
 		case $a in
 		carp+([0-9]):) ifconfig ${a%:} down ;;
@@ -302,10 +307,10 @@ trap "echo 'Boot interrupted.'; exit 1" 3
 
 umount -a >/dev/null 2>&1
 mount -a -t nonfs,vnd
-mount -uw /		# root on nfs requires this, others aren't hurt
+mount -uw /		# root on nfs requires this, others aren't hurt.
 rm -f /fastboot		# XXX (root now writeable)
 
-# set flags on ttys.  (do early, in case they use tty for SLIP in netstart)
+# Set flags on ttys.  (Do early, in case they use tty for SLIP in netstart.)
 echo 'setting tty flags'
 ttyflags -a
 
@@ -335,7 +340,7 @@ if [ X"${pf}" != X"NO" ]; then
 	RULES="$RULES\npass out proto carp !received-on any keep state (no-sync)"
 	case `sysctl vfs.mounts.nfs 2>/dev/null` in
 	*[1-9]*)
-		# don't kill NFS
+		# Don't kill NFS.
 		RULES="set reassemble yes no-df\n$RULES"
 		RULES="$RULES\npass in proto { tcp, udp } from any port { sunrpc, nfsd } to any"
 		RULES="$RULES\npass out proto { tcp, udp } from any to any port { sunrpc, nfsd } !received-on any"
@@ -345,13 +350,13 @@ if [ X"${pf}" != X"NO" ]; then
 	pfctl -e
 fi
 
-# Fill net.inet.(tcp|udp).baddynamic lists from /etc/services
+# Fill net.inet.(tcp|udp).baddynamic lists from /etc/services.
 fill_baddynamic udp
 fill_baddynamic tcp
 
 sysctl_conf
 
-# set hostname, turn on network
+# Set hostname, turn on network.
 echo 'starting network'
 ifconfig -g carp carpdemote 128
 if [ -f /etc/resolv.conf.save ]; then
@@ -359,13 +364,14 @@ if [ -f /etc/resolv.conf.save ]; then
 	touch /etc/resolv.conf
 fi
 sh /etc/netstart
-dmesg > /dev/random	# any write triggers a rekey
+dmesg >/dev/random	# Any write triggers a rekey.
 
+# Load pf rules and bring up pfsync interface.
 if [ X"${pf}" != X"NO" ]; then
-	if [ -f ${pf_rules} ]; then
-		pfctl -f ${pf_rules}
+	if [ -f /etc/pf.conf ]; then
+		pfctl -f /etc/pf.conf
 	fi
-	# bring up pfsync after the working ruleset has been loaded
+	# Bring up pfsync after the working ruleset has been loaded.
 	if [ -f /etc/hostname.pfsync0 ]; then
 		sh /etc/netstart pfsync0
 	fi
@@ -376,12 +382,12 @@ mount -s /var >/dev/null 2>&1
 
 random_seed
 
-# clean up left-over files
+# Clean up left-over files.
 rm -f /etc/nologin /var/spool/lock/LCK.* /var/spool/uucp/STST/*
 (cd /var/run && { rm -rf -- *; install -c -m 664 -g utmp /dev/null utmp; })
 (cd /var/authpf && rm -rf -- *)
 
-# save a copy of the boot messages
+# Save a copy of the boot messages.
 dmesg >/var/run/dmesg.boot
 
 make_keys
@@ -391,9 +397,10 @@ start_daemon syslogd ldattach pflogd nsd unbound ntpd
 start_daemon iscsid isakmpd iked sasyncd ldapd npppd
 echo '.'
 
+# Load IPsec rules.
 if [ X"${ipsec}" != X"NO" ]; then
-	if [ -f ${ipsec_rules} ]; then
-		ipsecctl -f ${ipsec_rules}
+	if [ -f /etc/ipsec.conf ]; then
+		ipsecctl -f /etc/ipsec.conf
 	fi
 fi
 
@@ -408,12 +415,12 @@ echo '.'
 mount -a
 swapctl -A -t noblk
 
-# check and mount networked filesystems
+# Check and mount networked filesystems.
 do_fsck -N
 mount -a -N
 
-# /var/crash should be a directory or a symbolic link
-# to the crash directory if core dumps are to be saved.
+# /var/crash should be a directory or a symbolic link to the crash directory
+# if core dumps are to be saved.
 if [ -d /var/crash ]; then
 	savecore ${savecore_flags} /var/crash
 fi
@@ -430,7 +437,7 @@ dev_mkdb
 chmod 666 /dev/tty[pqrstuvwxyzPQRST]*
 chown root:wheel /dev/tty[pqrstuvwxyzPQRST]*
 
-# check the password temp/lock file
+# Check the password temp/lock file.
 if [ -f /etc/ptmp ]; then
 	logger -s -p auth.err \
 	    'password file may be incorrect -- /etc/ptmp exists'
@@ -438,8 +445,8 @@ fi
 
 echo clearing /tmp
 
-# prune quickly with one rm, then use find to clean up /tmp/[lqv]*
-# (not needed with mfs /tmp, but doesn't hurt there...)
+# Prune quickly with one rm, then use find to clean up /tmp/[lqv]*
+# (not needed with mfs /tmp, but doesn't hurt there...).
 (cd /tmp && rm -rf [a-km-pr-uw-zA-Z]*)
 (cd /tmp &&
     find . -maxdepth 1 ! -name . ! -name lost+found ! -name quota.user \
@@ -448,19 +455,19 @@ echo clearing /tmp
 setup_X_sockets
 
 [ -f /etc/rc.securelevel ] && sh /etc/rc.securelevel
-# rc.securelevel did not specifically set -1 or 2, so select the default: 1
+# rc.securelevel did not specifically set -1 or 2, so select the default: 1.
 if [ `sysctl -n kern.securelevel` -eq 0 ]; then
 	sysctl kern.securelevel=1
 fi
 
-# patch /etc/motd
+# Patch /etc/motd.
 if [ ! -f /etc/motd ]; then
 	install -c -o root -g wheel -m 664 /dev/null /etc/motd
 fi
 if T=`mktemp /tmp/_motd.XXXXXXXXXX`; then
-	sysctl -n kern.version | sed 1q > $T
-	echo "" >> $T
-	sed '1,/^$/d' < /etc/motd >> $T
+	sysctl -n kern.version | sed 1q >$T
+	echo "" >>$T
+	sed '1,/^$/d' </etc/motd >>$T
 	cmp -s $T /etc/motd || cp $T /etc/motd
 	rm -f $T
 fi
@@ -469,7 +476,7 @@ if [ X"${accounting}" = X"YES" ]; then
 	if [ ! -f /var/account/acct ]; then
 		touch /var/account/acct
 	fi
-	echo 'turning on accounting';	accton /var/account/acct
+	echo 'turning on accounting'; accton /var/account/acct
 fi
 
 if [ -f /sbin/ldconfig ]; then
@@ -483,11 +490,11 @@ if [ -f /sbin/ldconfig ]; then
 	ldconfig $shlib_dirs
 fi
 
-echo 'preserving editor files.';	/usr/libexec/vi.recover
+echo 'preserving editor files.'; /usr/libexec/vi.recover
 
 echo -n 'starting network daemons:'
 start_daemon ldomd sshd snmpd ldpd ripd ospfd ospf6d bgpd ifstated
-start_daemon relayd dhcpd dhcrelay mrouted dvmrpd
+start_daemon relayd dhcpd dhcrelay mrouted dvmrpd radiusd
 
 if ifconfig lo0 inet6 >/dev/null 2>&1; then
 	fw=`sysctl -n net.inet6.ip6.forwarding`
@@ -501,7 +508,7 @@ start_daemon ftpproxy tftpd tftpproxy identd inetd rarpd bootparamd
 start_daemon rbootd mopd spamd spamlogd sndiod
 echo '.'
 
-# If rc.firstime exists, run it just once, and make sure it is deleted
+# If rc.firsttime exists, run it just once, and make sure it is deleted.
 if [ -f /etc/rc.firsttime ]; then
 	mv /etc/rc.firsttime /etc/rc.firsttime.run
 	. /etc/rc.firsttime.run 2>&1 | tee /dev/tty |
@@ -509,7 +516,7 @@ if [ -f /etc/rc.firsttime ]; then
 fi
 rm -f /etc/rc.firsttime.run
 
-# Run rc.d(8) scripts from packages
+# Run rc.d(8) scripts from packages.
 if [ -n "${pkg_scripts}" ]; then
 	echo -n 'starting package daemons:'
 	for _r in $pkg_scripts; do
