create branch 2.1

diff --git a/src/etc/weekly b/src/etc/weekly
--- a/src/etc/weekly
+++ b/src/etc/weekly
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-#	$OpenBSD$
+#	$OpenBSD: weekly,v 1.6 1997/01/04 01:36:52 millert Exp $
 #
 
 PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/libexec
@@ -15,6 +15,7 @@ if [ -f /etc/weekly.local ];then
 	. /etc/weekly.local
 fi
 
+
 #echo ""
 #echo "Removing old .o files:"
 #find /usr/src -name '*.o' -atime +21 -print -a -exec rm -f {} \;
@@ -28,18 +29,22 @@ fi
 #	echo "looking for checked out files:"
 #	TDIR=/tmp/_checkout$$
 #
-#	mkdir $TDIR
-#	for file in `find -f /usr/src ! -fstype local -prune -or \
-#	    -name 'p.*' -print | egrep 'SCCS/p\.'`; do
-#		owner=`awk '{ print $3 }' $file`
-#		echo "$owner	$file"
-#		echo $file >> $TDIR/$owner
-#	done | sed -e 's,SCCS/p.,,'
-#	for file in $TDIR/*; do
-#		sed -e 's,SCCS/p.,,' $file | \
-#		    Mail -s 'checked out files' `basename $file`
-#	done
-#	rm -rf $TDIR
+#	if ! mkdir $TDIR ; then
+#		echo "temp dir $TDIR already exists!  Probable spoof attempt."
+#		ls -alF $TDIR
+#	else
+#		for file in `find -f /usr/src ! -fstype local -prune -or \
+#		    -name 'p.*' -print | egrep 'SCCS/p\.'`; do
+#			owner=`awk '{ print $3 }' $file`
+#			echo "$owner	$file"
+#			echo $file >> $TDIR/$owner
+#		done | sed -e 's,SCCS/p.,,'
+#		for file in $TDIR/*; do
+#			sed -e 's,SCCS/p.,,' $file | \
+#			    Mail -s 'checked out files' `basename $file`
+#		done
+#		rm -rf $TDIR
+#	fi
 #fi
 
 if [ -f /usr/lib/uucp/clean.weekly ]; then
@@ -53,11 +58,21 @@ echo ""
 
 echo ""
 if [ -f /var/db/locate.database ]; then
-	echo "Rebuilding locate database:"
-	chmod 644 /var/db/locate.database
-	chown nobody.nobody /var/db/locate.database
-	echo /usr/libexec/locate.updatedb | nice -5 su -m nobody 2>/dev/null
-	chown root.wheel /var/db/locate.database
+	TMP=`mktemp /var/db/locate.database.XXXXXX`
+	if [ $? -eq 0 ]; then
+		trap 'rm -f $TMP' 0 1 15
+		echo "Rebuilding locate database:"
+		echo "/usr/libexec/locate.updatedb --fcodes=-" | nice -5 su -m nobody 2>/dev/null 1>$TMP
+		if [ -s "$TMP" ]; then
+			chmod 444 $TMP
+			chown root.wheel $TMP
+			mv -f $TMP /var/db/locate.database
+		else
+			echo "Not installing locate database; zero size"
+		fi
+	else
+		echo "Not rebuilding locate database; can't create temp file"
+	fi
 else
 	echo "Not rebuilding locate database; no /var/db/locate.database"
 fi
